#!/bin/bash
#My public bash functions
#Dan Sullivan
#use source ~/.functions to load
#declare -F to list functions from bash 
#test_function straight from bash to check it (esists in this file)

show_date () {
	echo `date +%m`.`date +%d`.`date +%y`
}

test_function () {
	echo "whatever"
} 

#Take a time-stamped snapshot of my Win7 virtualbox instantiation.
snapwin7 () {
	vboxmanage snapshot Win7 take function.`date +%m`.`date +%d`.`date +%y`
}

snapxpucad () {
	vboxmanage snapshot "XP (UCAD)" take function.`date +%m`.`date +%d`.`date +%y`
}

#kill every open RDP session on my box.
rdpkill () {
	for i in `ps -ef | grep rdesktop | grep -v grep | awk '{ print $2 }'`; do kill $i; done
}

killrdp () {
	rdpkill
}

dirty_bash_prompt () {
	PS1="--(\u@\h)-(\w)--\n> "
}

killwin7rdp () {
	kill `ps -ef | grep rdesktop | grep -v grep | grep win7.bsd.uchicago.edu:3389 | awk '{ print $ 2 } '`
}

pdf () {
	evince $1 
}

ldap() {
	ldapsearch -v -x -LLL -h ldap.uchicago.edu -p 389 -b dc=uchicago,dc=edu uid=$1
}

#query google's dns servers
qg() {
	dig @8.8.8.8 $1
}
